### ISSUE TITLE
edge/components out of date

### ISSUE THREAD

**Issue by xnox** [canonical/snapcraft#4576]
### Bug Description

building snap `build-base:core24` works with latest/edge but not if one uses latest/edge/components

Please auto build latest/edge/components and keep it up to date

```diff
$ diff 10568/lib/python3.10/site-packages/snapcraft/providers.py 10607/lib/python3.10/site-packages/snapcraft/providers.py | head
diff --git a/10568/lib/python3.10/site-packages/snapcraft/providers.py b/10607/lib/python3.10/site-packages/snapcraft/providers.py
index e7c389c0ba..6f676258fd 100644
--- a/10568/lib/python3.10/site-packages/snapcraft/providers.py
+++ b/10607/lib/python3.10/site-packages/snapcraft/providers.py
@@ -42,6 +42,7 @@ SNAPCRAFT_BASE_TO_PROVIDER_BASE = {
     "core18": bases.BuilddBaseAlias.BIONIC,
     "core20": bases.BuilddBaseAlias.FOCAL,
     "core22": bases.BuilddBaseAlias.JAMMY,
+    "core24": bases.BuilddBaseAlias.DEVEL,
     "devel": bases.BuilddBaseAlias.DEVEL,
```

### To Reproduce

snapcraft against snapcraft.yaml with build-base:core24

### Environment

ubuntu

### snapcraft.yaml

```shell
build-base:core24
```

### Relevant log output

```shell
$ snapcraft 
Traceback (most recent call last):
  File "/snap/snapcraft/10568/bin/snapcraft", line 8, in <module>
    sys.exit(run())
  File "/snap/snapcraft/10568/lib/python3.10/site-packages/snapcraft/cli.py", line 258, in run
    _run_dispatcher(dispatcher, global_args)
  File "/snap/snapcraft/10568/lib/python3.10/site-packages/snapcraft/cli.py", line 230, in _run_dispatcher
    dispatcher.run()
  File "/snap/snapcraft/10568/lib/python3.10/site-packages/craft_cli/dispatcher.py", line 487, in run
    return self._loaded_command.run(self._parsed_command_args)
  File "/snap/snapcraft/10568/lib/python3.10/site-packages/snapcraft/commands/lifecycle.py", line 265, in run
    super().run(parsed_args)
  File "/snap/snapcraft/10568/lib/python3.10/site-packages/snapcraft/commands/lifecycle.py", line 138, in run
    parts_lifecycle.run(self.name, parsed_args)
  File "/snap/snapcraft/10568/lib/python3.10/site-packages/snapcraft/parts/lifecycle.py", line 112, in run
    _run_command(
  File "/snap/snapcraft/10568/lib/python3.10/site-packages/snapcraft/parts/lifecycle.py", line 158, in _run_command
    _run_in_provider(project, command_name, parsed_args)
  File "/snap/snapcraft/10568/lib/python3.10/site-packages/snapcraft/parts/lifecycle.py", line 490, in _run_in_provider
    build_base = providers.SNAPCRAFT_BASE_TO_PROVIDER_BASE[snapcraft_base]
KeyError: 'core24'
```

**Comment by mr-cal** [comment]
Thanks, I'll pull in the latest changes from `main` ASAP and ensure other changes get pulled into this branch as well.

**Comment by mr-cal** [comment]
Yikes, this should have been released via https://github.com/canonical/snapcraft/actions/runs/7906910487/job/21582787837#step:7:38

Let me test it

**Comment by xnox** [comment]
but it did, and still doesn't have the bit i need. hmmmm let me check stuff too.

**Comment by mr-cal** [comment]
Yes, please re-open if it doesn't work.

I see it locally and I was able to build a core24 snap with components:
```
> grep "core24" -C5 /snap/snapcraft/10646/lib/python3.10/site-packages/snapcraft/providers.py

SNAPCRAFT_BASE_TO_PROVIDER_BASE = {
    "core18": bases.BuilddBaseAlias.BIONIC,
    "core20": bases.BuilddBaseAlias.FOCAL,
    "core22": bases.BuilddBaseAlias.JAMMY,
    "core24": bases.BuilddBaseAlias.NOBLE,
    "devel": bases.BuilddBaseAlias.DEVEL,
}
```

**Comment by xnox** [comment]
it works locally, but launchpad needs a matching config change too now..... https://bugs.launchpad.net/launchpad/+bug/2053056
