### ISSUE TITLE
Cannot build snaps in a 32-bit armhf container when running an arm64 kernel 

### ISSUE THREAD

**Issue by IsaacJT** [canonical/snapcraft#4627]
### Bug Description

This is a follow-up to the bug report posted on Launchpad: https://bugs.launchpad.net/snapcraft/+bug/1987627

Snapcraft is unable to snaps inside armhf containers when running on an arm64 host.

### To Reproduce

Create an armhf container on an arm64 host and try to build a Core22-based snap with Snapcraft.

### Environment

Building with destructive mode in an Ubuntu 22.04 armhf container on an arm64 host

### snapcraft.yaml

```shell
Any snapcraft.yaml for armhf
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/snap/snapcraft/10599/bin/snapcraft", line 8, in <module>
    sys.exit(run())
  File "/snap/snapcraft/10599/lib/python3.10/site-packages/snapcraft/cli.py", line 258, in run
    _run_dispatcher(dispatcher, global_args)
  File "/snap/snapcraft/10599/lib/python3.10/site-packages/snapcraft/cli.py", line 230, in _run_dispatcher
    dispatcher.run()
  File "/snap/snapcraft/10599/lib/python3.10/site-packages/craft_cli/dispatcher.py", line 487, in run
    return self._loaded_command.run(self._parsed_command_args)
  File "/snap/snapcraft/10599/lib/python3.10/site-packages/snapcraft/commands/lifecycle.py", line 265, in run
    super().run(parsed_args)
  File "/snap/snapcraft/10599/lib/python3.10/site-packages/snapcraft/commands/lifecycle.py", line 138, in run
    parts_lifecycle.run(self.name, parsed_args)
  File "/snap/snapcraft/10599/lib/python3.10/site-packages/snapcraft/parts/lifecycle.py", line 97, in run
    _expand_environment(
  File "/snap/snapcraft/10599/lib/python3.10/site-packages/snapcraft/parts/lifecycle.py", line 629, in _expand_environment
    info = craft_parts.ProjectInfo(
  File "/snap/snapcraft/10599/lib/python3.10/site-packages/craft_parts/infos.py", line 97, in __init__
    self._set_machine(arch)
  File "/snap/snapcraft/10599/lib/python3.10/site-packages/craft_parts/infos.py", line 310, in _set_machine
    raise errors.InvalidArchitecture(self._host_arch)
craft_parts.errors.InvalidArchitecture: Architecture 'armv8l' is not supported.
Make sure the architecture name is correct.
```

### Additional context

```
$ dpkg --print-architecture
armhf

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 22.04 LTS
Release: 22.04
Codename: jammy

$ uname -m
armv8l
```

Core20-based snaps build correctly on Ubuntu 20.04 in an armhf container on an arm64 host.

**Comment by mr-cal** [comment]
This is now supported in Snapcraft 9.1, due to a bunch of related upstream changes to support this.
