### ISSUE TITLE
No longer be able to use HTTP(S) proxies when building core24 snaps

### ISSUE THREAD

**Issue by brlin-tw** [canonical/snapcraft#4893]
### Bug Description

The `--http-proxy` and `--https-proxy` command-line options are no longer supported when building core24 snaps.

```
$ snapcraft pull --http-proxy http://192.168.49.1:8228
Usage: snapcraft [options] command [args]...
Try 'snapcraft pull -h' for help.

Error: unrecognized arguments: --http-proxy
```

Neither does setting the `http_proxy` and the `https_proxy` environment variables help:

```output
$ printenv | grep -i proxy
no_proxy=localhost
https_proxy=http://192.168.49.1:8228
http_proxy=http://192.168.49.1:8228

$ snapcraft --debug --verbose
Starting snapcraft, version 8.2.12                                                                                                                                       
Logging execution to '/home/brlin/.local/state/snapcraft/log/snapcraft-20240706-003735.686097.log'                                                                       
Launching managed ubuntu 24.04 instance...                                                                                                                               
Starting instance                                                                                                                                                        
Starting snapcraft, version 8.2.12                                                                                                                                       
Logging execution to '/tmp/snapcraft.log'                                                                                                                                

    ...stripped...
                                                                                                         
Pulling vrrtest                                                                                                                                                          
:: + set -o nounset                                                                                                                                                      
:: + craftctl default                                                                                                                                                    
:: error:                                                                                                                                                                
:: Traceback (most recent call last):                                                                                                                                    
::   File "/snap/snapcraft/current/lib/python3.10/site-packages/craft_parts/ctl.py", line 111, in main                                                                   
::     ret = CraftCtl.run(cmd, args)                                                                                                                                     
::   File "/snap/snapcraft/current/lib/python3.10/site-packages/craft_parts/ctl.py", line 45, in run                                                                     
::     _client(cmd, args)                                                                                                                                                
::   File "/snap/snapcraft/current/lib/python3.10/site-packages/craft_parts/ctl.py", line 98, in _client                                                                 
::     raise RuntimeError(message)                                                                                                                                       
:: RuntimeError: Failed to pull source: command ['git', 'clone', '--recursive', 'https://github.com/Nixola/VRRTest.git', '/root/parts/vrrtest/src'] exited with code 128.
:: + printf 'Error: Unable to run the default step handler.\n'                                                                                                           
:: Error: Unable to run the default step handler.                                                                                                                        
:: + exit 2                                                                                                                                                              
'override-pull' in part 'vrrtest' failed with code 2.                                                                                                                    
Launching shell on build environment...                                                                                                                                  
snapcraft-vrrtest-on-amd64-for-amd64-3209196 ../project# printenv | grep -i proxy
snapcraft-vrrtest-on-amd64-for-amd64-3209196 ../project#
```

Comparing the output of the `snapcraft build --help` command against core22 and core24 snaps reveal the following differences in supported command-line options:

* `--bind-ssh` (no longer available in core24)
* `--http-proxy` (no longer available in core24)
* `--https-proxy` (no longer available in core24)
*  `--ua-token` (no longer available in core24)
* `--enable-experimental-ua-services` (no longer available in core24)
* `--enable-experimental-plugins` (no longer available in core24)
* `--platform` (added in core24)

### To Reproduce

1. `mkdir test && cd test`
2. `snapcraft init`
3. `sed -i s@core22@core24@ snap/snapcraft.yaml`
4. `snapcraft pull --help`
5. Look for the `--http-proxy` and the `--https-proxy` command-line option.
6. 

### Snapcraft

8.2.12

### Operating system

Ubuntu 24.04

### snapcraft.yaml

```shell
name: my-snap-name # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
```

### Relevant log output

```shell
N/A
```

**Comment by brlin-tw** [comment]
I noticed that even building core20 snaps on Snapcraft 8.x:

```output
Snap Packaging for scrcpy$ snapcraft --verbose --use-lxd
Starting snapcraft, version 8.3.1                                                                                                                                        
Logging execution to '/home/brlin/.local/state/snapcraft/log/snapcraft-20240711-154140.224413.log'                                                                       
Launching a container.
Waiting for container to be ready
Waiting for network to be ready...
2024-07-11T07:42:15Z INFO Waiting for automatic snapd restart...
snapd 2.63 from Canonical✓ installed
"snapd" switched to the "latest/stable" channel

core20 20240416 from Canonical✓ installed
"core20" switched to the "latest/stable" channel

error: cannot perform the following tasks:
- Ensure prerequisites for "snapcraft" are available (cannot install snap base "core22": Post "https://api.snapcraft.io/v2/snaps/refresh": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers))
An error occurred when trying to execute 'snap install --classic /var/tmp/snapcraft.snap' with 'LXD': returned exit code 1.
```

This is no longer reproduced when I switched to the 7.x track.

**Comment by brlin-tw** [comment]
Here's the console session output while I'm reproducing this issue on a core20 snap:

[snapcraft-http-proxy-regression-reproduction.txt](https://github.com/user-attachments/files/16173939/snapcraft-http-proxy-regression-reproduction.txt)

**Comment by dbruno74** [comment]
Hi,
--http-proxy and --https-proxy can be passed as environment variables (http_proxy and https_proxy). no-proxy can also be passed this way too.

**Comment by mr-cal** [comment]
> --http-proxy and --https-proxy can be passed as environment variables (http_proxy and https_proxy). no-proxy can also be passed this way too.

Yes, this should now work for all 3 proxy variables in snapcraft 8.
