### ISSUE TITLE
Module error for snapcraft raised in override-build

### ISSUE THREAD

**Issue by sergiusens** [canonical/snapcraft#4912]
### Bug Description

Calling `craftctl default` raises a `ModuleNotFoundError` for `snapcraft_legacy`

### To Reproduce

Run Snapcraft 8.3.1 with ansel from https://github.com/sergiusens/ansel/tree/core24

### Environment

Ubuntu 22.04, Snapcraft 8.3.1 using the LXD provider

### snapcraft.yaml

```shell
.
```

### Relevant log output

```shell
2024-07-11 22:05:54.669 :: + snapcraftctl build                                                                                                                                              
2024-07-11 22:05:54.686 :: Traceback (most recent call last):                                                                                                                                
2024-07-11 22:05:54.686 ::   File "<string>", line 2, in <module>                                                                                                                            
2024-07-11 22:05:54.686 :: ModuleNotFoundError: No module named 'snapcraft_legacy'                                                                                                           
2024-07-11 22:05:54.861 'override-build' in part 'ansel' failed with code 1.                                                                                                                 
2024-07-11 22:05:54.864 Traceback (most recent call last):                                                                                                                                   
2024-07-11 22:05:54.864   File "/snap/snapcraft/12136/lib/python3.10/site-packages/craft_application/services/lifecycle.py", line 261, in run                                                
2024-07-11 22:05:54.864     aex.execute(action, stdout=stream, stderr=stream)                                                                                                                
2024-07-11 22:05:54.864   File "/snap/snapcraft/12136/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 327, in execute                                                   
2024-07-11 22:05:54.864     self._executor.execute(actions, stdout=stdout, stderr=stderr)                                                                                                    
2024-07-11 22:05:54.864   File "/snap/snapcraft/12136/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 137, in execute                                                   
2024-07-11 22:05:54.864     self._run_action(act, stdout=stdout, stderr=stderr)                                                                                                              
2024-07-11 22:05:54.864   File "/snap/snapcraft/12136/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 214, in _run_action                                               
2024-07-11 22:05:54.864     handler.run_action(action, stdout=stdout, stderr=stderr)                                                                                                         
2024-07-11 22:05:54.864   File "/snap/snapcraft/12136/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 170, in run_action                                            
2024-07-11 22:05:54.864     state = handler(step_info, stdout=stdout, stderr=stderr)                                                                                                         
2024-07-11 22:05:54.864   File "/snap/snapcraft/12136/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 309, in _run_build                                            
2024-07-11 22:05:54.865     self._run_step(                                                                                                                                                  
2024-07-11 22:05:54.865   File "/snap/snapcraft/12136/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 483, in _run_step                                             
2024-07-11 22:05:54.865     step_handler.run_scriptlet(                                                                                                                                      
2024-07-11 22:05:54.865   File "/snap/snapcraft/12136/lib/python3.10/site-packages/craft_parts/executor/step_handler.py", line 330, in run_scriptlet                                         
2024-07-11 22:05:54.865     raise errors.ScriptletRunError(                                                                                                                                  
2024-07-11 22:05:54.865 craft_parts.errors.ScriptletRunError: 'override-build' in part 'ansel' failed with code 1.                                                                           
2024-07-11 22:05:54.865 Review the scriptlet and make sure it's correct.                                                                                                                     
2024-07-11 22:05:54.865 Recommended resolution: Review the scriptlet and make sure it's correct.
```

**Comment by sergiusens** [comment]
Seems like using `snapcraftctl build` raises that ugly error

**Comment by aieri** [comment]
I'm also seeing this, just in a pull override.

snapcraft 8.3.1, Ubuntu 24.04, LXD 5.21.2 or 6.1

Relevant snapcraft.yaml triggering the error:

```
    override-pull: |                                                                    
      snapcraftctl pull                                                                 
      patch $SNAPCRAFT_PART_SRC/src/somefile.cpp < my.patch
```

Identical error, just triggered by a pull instead of a build

**Comment by mr-cal** [comment]
Oddly, I can't reproduce this on 8.3.2 and or latest/edge:

| version | reproducible? |
|--|--|
| 8.2.12 | yes |
| 8.3.0 | yes |
| 8.3.1 | yes |
| 8.3.2 | no |
| latest/edge (which will be 8.4) | no |

I don't see any changes in 8.3.2 that would affect this.

**Comment by mr-cal** [comment]
No longer reproducible with:

```yaml
name: hello-core22
base: core22
version: '0.1'
summary: hello
description: hello
grade: devel
confinement: devmode

architectures:
  - amd64
  - arm64

parts:
  my-part:
    plugin: nil
    override-build: |
      snapcraftctl build
```
