### ISSUE TITLE
snapcraft help fails on many commands

### ISSUE THREAD

**Issue by plars** [canonical/snapcraft#5169]
### Bug Description

On some commands such as promote, validate, revisions... you get error output when trying to do `snapcraft help <command>` or `snapcraft <command> -h`

### To Reproduce

run `snapcraft help <command>` with one of the above mentioned commands, and possibly others.

### Environment

Ubuntu, snapcraft 8.5.0

### snapcraft.yaml

```yaml
n/a
```

### Relevant log output

```shell
Internal error while loading snapcraft: IndexError('list index out of range')
Full execution log: '/home/plars/.local/state/snapcraft/log/snapcraft-20241206-152815.612091.log'
Traceback (most recent call last):
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_application/application.py", line 502, in _get_dispatcher
    global_args = dispatcher.pre_parse_args(sys.argv[1:], app_config)
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_cli/dispatcher.py", line 476, in pre_parse_args
    help_text = self._get_requested_help(cmd_args, app_config)
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_cli/dispatcher.py", line 358, in _get_requested_help
    return self._help_builder.get_command_help(command, command_options, output_format)
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_cli/helptexts.py", line 468, in get_command_help
    textblocks = builder(command, usage, parameters, options, other_command_names)
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_cli/helptexts.py", line 337, in _build_plain_command_help
    positional_args_lines.extend(_build_item_plain(title, text, max_title_len))
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_cli/helptexts.py", line 71, in _build_item_plain
    first = f"    {title:>{title_space}s}:  {wrapped_lines[0]}"
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_application/application.py", line 663, in run
    return_code = self._run_inner()
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/snapcraft/application.py", line 202, in _run_inner
    return_code = super()._run_inner()
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_application/application.py", line 610, in _run_inner
    dispatcher = self._get_dispatcher()
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/snapcraft/application.py", line 431, in _get_dispatcher
    return super()._get_dispatcher()
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_application/application.py", line 525, in _get_dispatcher
    if self.services.config.get("debug"):
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_application/services/service_factory.py", line 125, in __getattr__
    instance.setup()
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_application/services/config.py", line 163, in setup
    super().setup()
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_application/services/base.py", line 45, in setup
    emit.debug(f"Setting up {self.__class__.__name__}")
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_cli/messages.py", line 417, in func
    raise RuntimeError("Emitter is stopped already")
RuntimeError: Emitter is stopped already

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/snapcraft/13008/bin/snapcraft", line 8, in <module>
    sys.exit(main())
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/snapcraft/application.py", line 482, in main
    return app.run()
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_application/application.py", line 693, in run
    if self.services.config.get("debug"):
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_application/services/service_factory.py", line 125, in __getattr__
    instance.setup()
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_application/services/config.py", line 163, in setup
    super().setup()
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_application/services/base.py", line 45, in setup
    emit.debug(f"Setting up {self.__class__.__name__}")
  File "/snap/snapcraft/13008/lib/python3.10/site-packages/craft_cli/messages.py", line 417, in func
    raise RuntimeError("Emitter is stopped already")
RuntimeError: Emitter is stopped already
```

**Comment by mr-cal** [comment]
Thanks for the report. I can reproduce this too.  

Looks like snapcraft is missing a help field for some arguments, such as [this one](https://github.com/canonical/snapcraft/blob/70b468543bf5b223bb5dfb9f068c73215f9d0db6/snapcraft/commands/legacy.py#L116).
